syntax = "proto3";
package character_service;

option go_package = "github.com/alsadx/GM-Tool/character-service/gen";

import "character.proto";

service CharacterService {
  rpc CreateCharacter(CreateCharRequest) returns (CreateCharResponse);
  rpc GetCharacter(GetCharRequest) returns (GetCharResponse);
  rpc UpdateCharacter(UpdateCharRequest) returns (UpdateCharResponse);
  rpc DeleteCharacter(DeleteCharRequest) returns (DeleteCharResponse);
  rpc ListCharacters(ListCharRequest) returns (ListCharResponse);

  rpc GainExp(ExpRequest) returns (CharacterResponse);
  rpc RemoveExp(ExpRequest) returns (CharacterResponse);
  rpc TakeDamage(DamageRequest) returns (CharacterResponse);
  rpc Heal(HealRequest) returns (CharacterResponse);
  rpc LevelUp(LevelRequest) returns (CharacterResponse);
  rpc LevelDown(LevelRequest) returns (CharacterResponse);
  rpc SetLevel(SetLevelRequest) returns (CharacterResponse);
  rpc AddHitDice(HitDiceRequest) returns (CharacterResponse);
  rpc AddTempHp(TempHpRequest) returns (CharacterResponse);
  rpc CheckAbility(CheckAbilityRequest) returns (CheckResponse);
  rpc CheckSkill(CheckSkillRequest) returns (CheckResponse);
  rpc GetStatus(GetStatusRequest) returns (StatusResponse);
}

message ExpRequest {
  int64 character_id = 1;
  int32 amount = 2;
}

message DamageRequest {
  int64 character_id = 1;
  int32 damage = 2;
}

message HealRequest {
  int64 character_id = 1;
  int32 amount = 2;
}

message LevelRequest {
  int64 character_id = 1;
}

message SetLevelRequest {
  int64 character_id = 1;
  int32 level = 2;
}

message HitDiceRequest {
  int64 character_id = 1;
  int32 dice_type = 2;
}

message TempHpRequest {
  int64 character_id = 1;
  int32 amount = 2;
}

message CheckAbilityRequest {
  int64 character_id = 1;
  int32 ability = 2;
}

message CheckSkillRequest {
  int64 character_id = 1;
  int32 skill = 2;
}

message CheckResponse {
  int32 dice_result = 1;
  int32 bonus = 2;
  int32 total = 3;
}

message GetStatusRequest {
  int64 character_id = 1;
}

message StatusResponse {
  int32 current_hp = 1;
  int32 temp_hp = 2;
  int32 max_hp = 3;
  bool is_knocked = 4;
  int32 level = 5;
  int32 current_exp = 6;
  int32 exp_to_next = 7;
}

message CharacterResponse {
  character.Character character = 1;
}

message CreateCharRequest {
  int64 id = 1;
  int64 owner_id = 2;
  string name = 3;
  string class_name = 4;
  string subclass = 5;
  string race = 6;
}

message CreateCharResponse {
  character.Character character = 1;
}

message GetCharRequest {
  int64 id = 1;
}

message GetCharResponse {
  character.Character character = 1;
}

message UpdateCharRequest {
  character.Character character = 1;
}

message UpdateCharResponse {
  character.Character character = 1;
}

message DeleteCharRequest {
  int64 id = 1;
}

message DeleteCharResponse {
  bool success = 1;
}

message ListCharRequest {
  int64 owner_id = 1;
}

message ListCharResponse {
  repeated character.Character characters = 1;
}