networks:
  app-network:
    driver: bridge

services:
  # SSO-сервис
  sso-service:
    networks: 
      - app-network
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: sso
    ports:
      - "50051:50051" # Порт, на котором работает SSO-сервис
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=sso
      - MIGRATION_PATH=/app/migrations/
      - TEST_ENV=
      - CONFIG_PATH=/app/config/local.yaml
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:50051", "-service=auth.AuthService/HealthCheck"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: always

  # PostgreSQL
  postgres:
    networks: 
      - app-network
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sso
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: