version: 3

tasks:
  migrate:
    desc: "Apply database migrations"
    cmds:
      - go run ./cmd/migrator/main.go --db-url="postgres:@localhost:5431/sso?sslmode=disable" --migrations-path="./migrations" --migrations-table="campaign_migrations"

  run:
    desc: "Run the server"
    cmds:
      - go run cmd/campaign_tool/main.go --config config/local.yaml  

  test-migrate:
    desc: "Database migrations for testing"
    cmds:
      - go run ./cmd/migrator/main.go --db-url="postgres:@localhost:5431/sso?sslmode=disable" --migrations-path="./tests/migrations" --migrations-table="test_migrations"

  mockgen:
    cmds:
      - mockgen -source=./internal/services/campaign/campaign.go -destination=./tests/mocks/game_mocks.go -package=mocks

  gen-proto:
    desc: "Generate code from proto file"
    cmds:
      - protoc -I protos/proto protos/proto/*.proto --go_out=protos/campaignv1 --go_opt=paths=source_relative --go-grpc_out=protos/campaignv1 --go-grpc_opt=paths=source_relative