env: "local"
postgres:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "postgres"
  database: "sso"
  maxConn: 10

grpc:
  port: 50051
  timeout: 5s

auth:
  accessTokenTTL: 1h
  refreshTokenTTL: 720h #30 days